### ISSUE TITLE
Debug or logging possibility?

### ISSUE THREAD

**Issue by erikdubois** [trizen/obmenu-generator#12]
Hi, is there a debug or log file to see what goes wrong.
When creating a menu with surfn icons, something goes wrong.
cpu 100% and system hangs.

**Comment by trizen** [comment]
Hi Erik!

There is a circular inheritance in https://github.com/erikdubois/Surfn/blob/master/Surfn/index.theme#L4 (Surfn inherits itself), which caused [Linux::DesktopFiles](https://metacpan.org/release/TRIZEN/Linux-DesktopFiles-0.13) to get stuck into an infinite loop. 

This issue has been fixed in version  0.13 of Linux::DesktopFiles.

In obmenu-generator, unfortunately, we don't have a debug functionality. The best we can do, is to use [Devel::Trace](https://metacpan.org/pod/Devel::Trace), as:

```
perl -d:Trace /usr/bin/obmenu-generator -i -s -c -d
```

or `strace`, as:

```
strace obmenu-generator -i -s -c -d
```

**Comment by erikdubois** [comment]
wow - am i glad i asked the question - how did that get in there... thanks

**Comment by erikdubois** [comment]
![2017-06-03--1496491164_3840x1080_scrot](https://cloud.githubusercontent.com/assets/10594806/26753361/e378edac-4864-11e7-9c73-c79fa32ac4d3.png)
SOOOOOO happy

**Comment by erikdubois** [comment]
#archlabs what did you expect ;-)
your application is standard included
