### ISSUE TITLE
French, German, ... languages for obmenu-generator

### ISSUE THREAD

**Issue by archmerge** [trizen/obmenu-generator#18]
Hi, 
Can this scenario be accomplished.
We install ArchMerge in French. Xfce shows all menu's in French.
We go to openbox. Only pipemenu places is in French.
Can we have the menu's generated from Obmenu-generator also in French.
If so... how?
This is an example of a French installation.
![github](https://user-images.githubusercontent.com/31759042/31582618-eb95de0e-b188-11e7-973f-64050c92c1eb.png)

**Comment by trizen** [comment]
Hi. See the example in the `config.pl` file for `name_keys`.

**Comment by trizen** [comment]
After thinking a little bit more about this, I think we can do better.

In [this commit](https://github.com/trizen/obmenu-generator/commit/3564424e92c70233810ad557c1407793a28c8396), I added experimental locale support, which automatically detects what language to use for the name of each entry, based on `(LC_ALL LC_MESSAGES LANGUAGE LANG)` (more info: [here](https://metacpan.org/source/MICHIELB/File-DesktopEntry-0.22/lib/File/DesktopEntry.pm)).

This change requires a new dependency: [File::DesktopEntry](https://metacpan.org/pod/File::DesktopEntry) (available as `perl-file-desktopentry` in the Arch extra repository).

In order to test this new feature, please:
* Install `Linux::DesktopFiles` version 0.23
* Install `File::DesktopEntry`
* Execute: 
  * `git clone https://github.com/trizen/obmenu-generator`
  * `perl obmenu-generator/obmenu-generator -d -i -s -c`

**Comment by trizen** [comment]
Locale support has been added in version 0.82. Closing this now. Feel free to re-open it if something is not working as expected.

**Comment by luca-vercelli** [comment]
Please, can you explain how this works?  I am using version 0.85, however I still see English menus only.

My environment has: LANG=it_IT.UTF-8
No LC_ALL, no LC_MESSAGES, no LANGUAGE

**Comment by trizen** [comment]
See: https://metacpan.org/release/File-DesktopEntry/source/lib/File/DesktopEntry.pm

File::DesktopEntry uses the language data from the `.desktop` files (`/usr/share/applications/*.desktop`).

However, not many applications have different names in different languages, therefore the change may not be visible.

Additionally, the name of the categories have to be translated manually in the `schema.pl` file.
