### ISSUE TITLE
Permission denied at /usr/bin/obmenu-generator line 273.

### ISSUE THREAD

**Issue by IlhamSetiawan** [trizen/obmenu-generator#23]
hello i am using debian 9, and i tried to make a menu with this software, but i found the problem
![mas](https://user-images.githubusercontent.com/37190439/43420681-1aa774da-9434-11e8-8379-54bec6df8efe.png)I've tried with chmod + x but it did not work
'm using obmenu version 0.66

**Comment by trizen** [comment]
Hi. As the error message says, `obmenu-generator` fails to create its configuration file because it doesn't have permission to do so.

Try to fix the permissions in the `~/.config/obmenu-generator` directory or delete the directory entirely and run `obmenu-generator` again as a normal user (without sudo), which would allow it to create the directory and the configuration file with correct permissions.

**Comment by IlhamSetiawan** [comment]
successful, thank you
![os](https://user-images.githubusercontent.com/37190439/43425347-90435c20-947c-11e8-8247-86daacbbf1a6.png)

**Comment by trizen** [comment]
Awesome. :)
